In [1]:
import pandas as pd
import lxml
import requests
import yfinance as yf
from io import StringIO

In [2]:
url= "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [3]:
response=requests.get(url, headers=headers)

sp500=pd.read_html(StringIO(response.text))[0]
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [4]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [5]:
# list of ticker symbols for download (Needs to be done for S&P 500)
tickerStrings = sp500['Symbol'].tolist()

In [24]:
df = yf.download(tickerStrings, group_by='Ticker', period='1d')

[*******               14%                       ]  71 of 503 completed$MGM: possibly delisted; no price data found  (period=1d)
[*********             19%                       ]  97 of 503 completed$ALB: possibly delisted; no price data found  (period=1d)
[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['MGM', 'ALB']: possibly delisted; no price data found  (period=1d)

In [25]:
df

Ticker             GM                                              MDT  \
Price            Open    High        Low   Close     Volume       Open
Date
2026-06-23        NaN     NaN        NaN     NaN        NaN        NaN
2026-06-24  79.129997  80.569  79.080002  79.625  4810437.0  80.120003

Ticker                                                  ...      O             \
Price            High        Low      Close     Volume  ...   Open       High
Date                                                    ...
2026-06-23        NaN        NaN        NaN        NaN  ...    NaN        NaN
2026-06-24  82.089996  80.120003  80.599998  4450147.0  ...  61.77  62.455002

Ticker                                         HOOD                         \
Price         Low      Close     Volume        Open        High        Low
Date
2026-06-23    NaN        NaN        NaN         NaN         NaN        NaN
2026-06-24  61.48  62.169998  4059659.0  102.346001  104.269997  96.294998

Ticker
Price        Close      Volume
Date
2026-06-23     NaN         NaN
2026-06-24  97.195  24692367.0

[2 rows x 2517 columns]

In [26]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-06-23,GM,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-06-23,MDT,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-06-23,NDSN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-06-23,UNP,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-06-23,UBER,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1001,2026-06-24,ULTA,465.899994,481.739990,459.000000,474.605011,690981.0,NaN
1002,2026-06-24,ZBRA,238.619995,249.419998,237.000000,246.660004,548355.0,NaN
1003,2026-06-24,LITE,824.744995,866.429993,803.330017,835.440002,3431691.0,NaN
1004,2026-06-24,O,61.770000,62.455002,61.480000,62.169998,4059659.0,NaN
1005,2026-06-24,HOOD,102.346001,104.269997,96.294998,97.195000,24692367.0,NaN

In [27]:
downloaded_tickers=set(df["Ticker"].unique())

In [28]:
missing = set(tickerStrings) - downloaded_tickers

missing

set()

In [29]:
len(downloaded_tickers)

503

In [30]:
row_counts = df.groupby("Ticker").size()
print(row_counts.sort_values())

Ticker
A       2
AAPL    2
ABBV    2
ABNB    2
ABT     2
       ..
XYZ     2
YUM     2
ZBH     2
ZBRA    2
ZTS     2
Length: 503, dtype: int64

In [31]:
for ticker in ["FRT", "PHM", "SYY"]:
    count = (df["Ticker"] == ticker).sum()
    print(f"{ticker}: {count} rows")

FRT: 2 rows
PHM: 2 rows
SYY: 2 rows

In [32]:
df.columns.name = None
df

,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-06-23,GM,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-06-23,MDT,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-06-23,NDSN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-06-23,UNP,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-06-23,UBER,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1001,2026-06-24,ULTA,465.899994,481.739990,459.000000,474.605011,690981.0,NaN
1002,2026-06-24,ZBRA,238.619995,249.419998,237.000000,246.660004,548355.0,NaN
1003,2026-06-24,LITE,824.744995,866.429993,803.330017,835.440002,3431691.0,NaN
1004,2026-06-24,O,61.770000,62.455002,61.480000,62.169998,4059659.0,NaN
1005,2026-06-24,HOOD,102.346001,104.269997,96.294998,97.195000,24692367.0,NaN

In [33]:
def validate_download(df, expected_tickers, ohlcv_cols=["Open", "High", "Low", "Close", "Volume"]):
    
    downloaded_tickers = set(df["Ticker"].unique())
    fully_missing = set(expected_tickers) - downloaded_tickers

    # Per-column null counts per ticker
    null_by_col = (
        df.groupby("Ticker")[ohlcv_cols]
        .apply(lambda x: x.isna().sum())
    )
    null_by_col["Total"] = null_by_col.sum(axis=1)
    has_nulls = null_by_col[null_by_col["Total"] > 0]

    # First and last valid (non-null) date per ticker
    valid_dates = (
        df[df["Close"].notna()]
        .groupby("Ticker")["Date"]
        .agg(
            first_valid_date="min",
            last_valid_date="max"
        )
    )

    # Get the earliest date in your entire dataset (start of your backfill window)
    backfill_start = df["Date"].min()
    
    # Count trading days between backfill start and first valid date per ticker
    # Trading days = number of dates that appear in your df for any ticker
    all_trading_days = df["Date"].drop_duplicates().sort_values()
    
    def count_trading_days_before(first_valid_date):
        return (all_trading_days < first_valid_date).sum()
    
    valid_dates["trading_days_before_listing"] = valid_dates["first_valid_date"].apply(
        count_trading_days_before
    )
    # Distinguish fully null vs partially null
    row_counts = df.groupby("Ticker").size()
    max_possible_nulls = row_counts * len(ohlcv_cols)
    fully_null_mask = has_nulls["Total"] == max_possible_nulls[has_nulls.index]
    fully_null = has_nulls[fully_null_mask]
    partially_null = has_nulls[~fully_null_mask].sort_values("Total", ascending=False)

    # Join valid date info onto partially null summary
    partially_null_summary = partially_null.join(valid_dates, how="left")

    # Report
    print(f"Total tickers expected:  {len(expected_tickers)}")
    print(f"Total tickers downloaded: {len(downloaded_tickers)}")

    if fully_missing:
        print(f"\nFully missing (not in df at all): {fully_missing}")
    else:
        print("\nFully missing: none")

    if len(fully_null) > 0:
        print(f"\nPresent but completely null (failed download):")
        print(fully_null.to_string())
    else:
        print("\nCompletely null tickers: none")

    if len(partially_null_summary) > 0:
        print(f"\nPartially null (recent IPO/spin-off) — breakdown by column + valid date range:\n")
        print(partially_null_summary.to_string())
    else:
        print("\nPartially null tickers: none")

    return fully_missing, fully_null, partially_null_summary

In [34]:
fully_missing, fully_null, partially_null = validate_download(df, tickerStrings)

Total tickers expected:  503
Total tickers downloaded: 503

Fully missing: none

Present but completely null (failed download):
        Open  High  Low  Close  Volume  Total
Ticker
ALB        2     2    2      2       2     10
MGM        2     2    2      2       2     10

Partially null (recent IPO/spin-off) — breakdown by column + valid date range:

        Open  High  Low  Close  Volume  Total first_valid_date last_valid_date  trading_days_before_listing
Ticker
A          1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AAPL       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ABBV       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ABNB       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ABT        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ACGL       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ACN        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ADBE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ADI        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ADM        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ADP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ADSK       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AEE        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AEP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AES        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AFL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AIG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AIZ        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AJG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AKAM       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ALGN       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ALL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ALLE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMAT       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMCR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMD        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AME        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMGN       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMT        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AMZN       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ANET       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AON        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AOS        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APA        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APD        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APH        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APO        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
APTV       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ARE        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ARES       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ATO        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AVB        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AVGO       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AVY        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AWK        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AXON       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AXP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
AZO        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BA         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BAC        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BALL       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BAX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BBY        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BDX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BEN        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BF-B       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BG         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BIIB       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BKNG       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BKR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BLDR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BLK        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BMY        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BNY        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BR         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BRK-B      1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BRO        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BSX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BX         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
BXP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
C          1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CAG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CAH        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CARR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CASY       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CAT        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CB         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CBOE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CBRE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CCI        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CCL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CDNS       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CDW        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CEG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CF         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CFG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CHD        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CHRW       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CHTR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CI         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CIEN       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CINF       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CL         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CLX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CMCSA      1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CME        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CMG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CMI        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CMS        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CNC        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CNP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COF        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COHR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COIN       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COO        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COP        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
COST       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CPAY       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CPRT       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CPT        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CRH        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CRL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CRM        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CRWD       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CSCO       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CSGP       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CSX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CTAS       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CTSH       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CTVA       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CVNA       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CVS        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
CVX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
D          1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DAL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DASH       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DD         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DDOG       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DE         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DECK       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DELL       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DG         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DGX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DHI        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DHR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DIS        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DLR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DLTR       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DOC        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DOV        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DOW        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DPZ        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DRI        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DTE        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DUK        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DVA        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DVN        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
DXCM       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EA         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EBAY       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ECL        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ED         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EFX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EG         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EIX        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EL         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ELV        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EME        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EMR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EOG        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EQIX       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EQR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EQT        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ERIE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ES         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ESS        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ETN        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
ETR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EVRG       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EW         1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EXC        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EXE        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EXPD       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EXPE       1     1    1      1       1      5       2026-06-24      2026-06-24                            1
EXR        1     1    1      1       1      5       2026-06-24      2026-06-24                            1
F          1     1    1      1       1      5       2026-06-24      2026-06-24                            1
FANG       1     1    1      1       1      5       2026-06-24      2026-06-24                            1

In [35]:
df.to_csv('daily_data_2306.csv')

In [36]:
ohlcv_cols=["Open", "High", "Low", "Close", "Volume"]

In [37]:
null_counts_by_ticker = (
    df.groupby("Ticker")[ohlcv_cols]
    .apply(lambda x: x.isna().sum().sum())  # total nulls across all OHLCV cols, per ticker
    .sort_values(ascending=False)
)

print(null_counts_by_ticker.head(10))

Ticker
ALB     10
MGM     10
NFLX     5
NI       5
NKE      5
NOC      5
NOW      5
NRG      5
NEM      5
NTAP     5
dtype: int64

In [38]:
yf.download("GOOG", group_by='Ticker', period='1d')

[*********************100%***********************]  1 of 1 completed

Ticker            GOOG
Price             Open        High        Low       Close    Volume
Date
2026-06-24  348.720001  352.829987  341.51001  343.339996  16445920