In [1]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 1.9 MB/s eta 0:00:00[31m2.6 MB/s eta 0:00:01
Requirement already satisfied: pandas>=1.3.0 in ./.venv/lib/python3.11/site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in ./.venv/lib/python3.11/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in ./.venv/lib/python3.11/site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in ./.venv/lib/python3.11/site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.1/510.1 kB 6.5 MB/s eta 0:00:00[36m0:00:01[36m0:00:01
Collecting peewee>=3.16.2
  Downloading peewee-4.1.0-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.1/155.1 kB 7.2 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./.venv/lib/python3.11/site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15
  Downloading curl_cffi-0.15.0-cp310-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl (10.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 11.4 MB/s eta 0:00:00m eta 0:00:0136m0:00:01
Collecting protobuf>=3.19.0
  Downloading protobuf-7.35.1-cp310-abi3-manylinux2014_aarch64.whl (328 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.8/328.8 kB 13.3 MB/s eta 0:00:00
Collecting websockets>=13.0
  Downloading websockets-16.0-cp311-cp311-manylinux2014_aarch64.manylinux_2_17_aarch64.manylinux_2_28_aarch64.whl (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.9/185.9 kB 8.9 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.11/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in ./.venv/lib/python3.11/site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Collecting rich
  Downloading rich-15.0.0-py3-none-any.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 10.2 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.11/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.11/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, protobuf, mdurl, markdown-it-py, rich, curl_cffi, yfinance
Successfully installed curl_cffi-0.15.0 markdown-it-py-4.2.0 mdurl-0.1.2 multitasking-0.0.13 peewee-4.1.0 protobuf-7.35.1 pytz-2026.2 rich-15.0.0 websockets-16.0 yfinance-1.4.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import yfinance as yf

In [4]:
df = yf.Ticker("MSFT")
df.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company has a strategic collaboration with Mayo Clinic, Inc. for the development of a frontier AI model for healthcare; and Global Objects, Inc. to build a retrieval-grounded generative AI world model. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 8,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 378.91,
 'open': 377.915,
 'dayLow': 373.28,
 'dayHigh': 381.37,
 'regularMarketPreviousClose': 378.91,
 'regularMarketOpen': 377.915,
 'regularMarketDayLow': 373.28,
 'regularMarketDayHigh': 381.37,
 'dividendRate': 3.64,
 'dividendYield': 0.92,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.20729999,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.103,
 'trailingPE': 22.610249,
 'forwardPE': 19.611391,
 'volume': 58466440,
 'regularMarketVolume': 58466440,
 'averageVolume': 36088063,
 'averageVolume10days': 38226240,
 'averageDailyVolume10Day': 38226240,
 'bid': 377.53,
 'ask': 379.35,
 'bidSize': 3,
 'askSize': 1,
 'marketCap': 2818348154880,
 'nonDilutedMarketCap': 2818348126697,
 'fiftyTwoWeekLow': 356.28,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 8.855128,
 'fiftyDayAverage': 412.9758,
 'twoHundredDayAverage': 451.34946,
 'trailingAnnualDividendRate': 3.56,
 'trailingAnnualDividendYield': 0.00939537,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2972744417280,
 'profitMargins': 0.39341998,
 'floatShares': 7417514905,
 'sharesOutstanding': 7428434704,
 'sharesShort': 88696120,
 'sharesShortPriorMonth': 79107882,
 'sharesShortPreviousMonthDate': 1777507200,
 'dateShortInterest': 1780012800,
 'sharesPercentSharesOut': 0.0119,
 'heldPercentInsiders': 0.0008,
 'heldPercentInstitutions': 0.75781,
 'shortRatio': 2.42,
 'shortPercentOfFloat': 0.0119,
 'impliedSharesOutstanding': 7428434704,
 'bookValue': 55.777,
 'priceToBook': 6.802087,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1774915200,
 'earningsQuarterlyGrowth': 0.231,
 'netIncomeToCommon': 125215997952,
 'trailingEps': 16.78,
 'forwardEps': 19.3459,
 'pegRatio': 1.22,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 9.34,
 'enterpriseToEbitda': 16.116,
 '52WeekChange': -0.20527858,
 'SandP52WeekChange': 0.2568333,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1779321600,
 'quoteType': 'EQUITY',
 'currentPrice': 379.4,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 561.38763,
 'targetMedianPrice': 555.0,
 'recommendationMean': 1.33929,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 55,
 'totalCash': 78227996672,
 'totalCashPerShare': 10.531,
 'ebitda': 184457003008,
 'totalDebt': 125431996416,
 'quickRatio': 1.142,
 'currentRatio': 1.283,
 'totalRevenue': 318272995328,
 'debtToEquity': 30.271,
 'revenuePerShare': 42.836,
 'returnOnAssets': 0.14814,
 'returnOnEquity': 0.34013999,
 'grossProfits': 217409994752,
 'freeCashflow': 37011251200,
 'operatingCashflow': 170141007872,
 'earningsGrowth': 0.234,
 'revenueGrowth': 0.183,
 'grossMargins': 0.68309,
 'ebitdaMargins': 0.57956004,
 'operatingMargins': 0.46326,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'regularMarketChangePercent': 0.129316,
 'regularMarketPrice': 379.4,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Microsoft Corporation',
 'corporateActions': [],
 'postMarketTime': 1781827198,
 'regularMarketTime': 1781812801,
 'longName': 'Microsoft Corporation',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 36088063,
 'fiftyTwoWeekLowChange': 23.119995,
 'fiftyTwoWeekLowChangePercent': 0.06489277,
 'fiftyTwoWeekRange': '356.28 - 555.45',
 'fiftyTwoWeekHighChange': -176.05002,
 'fiftyTwoWeekHighChangePercent': -0.31695023,
 'fiftyTwoWeekChangePercent': -20.527857,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1777492800,
 'earningsTimestampStart': 1785355200,
 'earningsTimestampEnd': 1785355200,
 'earningsCallTimestampStart': 1777498200,
 'earningsCallTimestampEnd': 1777498200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 16.78,
 'epsForward': 19.3459,
 'epsCurrentYear': 16.83996,
 'priceEpsCurrentYear': 22.529745,
 'fiftyDayAverageChange': -33.575806,
 'fiftyDayAverageChangePercent': -0.081302114,
 'twoHundredDayAverageChange': -71.94946,
 'twoHundredDayAverageChangePercent': -0.15940966,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': -0.06852379,
 'postMarketPrice': 379.14,
 'postMarketChange': -0.25997925,
 'regularMarketChange': 0.48999,
 'regularMarketDayRange': '373.28 - 381.37',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.1705}

In [5]:
df.calendar

{'Dividend Date': datetime.date(2026, 9, 10),
 'Ex-Dividend Date': datetime.date(2026, 8, 20),
 'Earnings Date': [datetime.date(2026, 7, 29)],
 'Earnings High': 4.89,
 'Earnings Low': 4.07,
 'Earnings Average': 4.23745,
 'Revenue High': 91239000000,
 'Revenue Low': 86900000000,
 'Revenue Average': 87655534780}

In [6]:
df.analyst_price_targets

{'current': 379.4,
 'high': 870.0,
 'low': 400.0,
 'mean': 561.38763,
 'median': 555.0}

In [7]:
df.quarterly_income_stmt

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31
Tax Effect Of Unusual Items,2.813900e+08,6.520000e+07,1.871500e+08,4.951251e+05,6.966000e+07
Tax Rate For Calcs,1.900000e-01,2.000000e-01,1.900000e-01,1.650420e-01,1.800000e-01
Normalized EBITDA,4.880400e+10,5.785400e+10,4.707500e+10,4.443100e+10,3.931800e+10
Total Unusual Items,1.481000e+09,3.260000e+08,9.850000e+08,3.000000e+06,3.870000e+08
Total Unusual Items Excluding Goodwill,1.481000e+09,3.260000e+08,9.850000e+08,3.000000e+06,3.870000e+08
Net Income From Continuing Operation Net Minority Interest,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Reconciled Depreciation,1.016700e+10,9.198000e+09,1.306100e+10,1.120300e+10,7.734000e+09
Reconciled Cost Of Revenue,2.682800e+10,2.597800e+10,2.404300e+10,2.401400e+10,2.191900e+10
EBITDA,5.028500e+10,5.818000e+10,4.806000e+10,4.443400e+10,3.970500e+10
EBIT,4.011800e+10,4.898200e+10,3.499900e+10,3.323100e+10,3.197100e+10
Net Interest Income,-4.800000e+07,1.040000e+08,2.780000e+08,1.540000e+08,3.000000e+06
Interest Expense,7.780000e+08,7.360000e+08,6.980000e+08,6.150000e+08,5.940000e+08
Interest Income,7.300000e+08,8.400000e+08,9.760000e+08,7.690000e+08,5.970000e+08
Normalized Income,3.057839e+10,3.819720e+10,2.694915e+10,2.723050e+10,2.550666e+10
Net Income From Continuing And Discontinued Operation,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Total Expenses,4.448800e+10,4.299800e+10,3.971200e+10,4.211800e+10,3.806600e+10
Total Operating Income As Reported,3.839800e+10,3.827500e+10,3.796100e+10,3.432300e+10,3.200000e+10
Diluted Average Shares,7.445000e+09,7.460000e+09,7.466000e+09,7.461000e+09,7.461000e+09
Basic Average Shares,7.426000e+09,7.431000e+09,7.433000e+09,7.432000e+09,7.434000e+09
Diluted EPS,4.270000e+00,5.160000e+00,3.720000e+00,3.650000e+00,3.460000e+00
Basic EPS,4.280000e+00,5.180000e+00,3.730000e+00,3.660000e+00,3.470000e+00
Diluted NI Availto Com Stockholders,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Net Income Common Stockholders,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Net Income,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Net Income Including Noncontrolling Interests,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Net Income Continuous Operations,3.177800e+10,3.845800e+10,2.774700e+10,2.723300e+10,2.582400e+10
Tax Provision,7.562000e+09,9.788000e+09,6.554000e+09,5.383000e+09,5.553000e+09
Pretax Income,3.934000e+10,4.824600e+10,3.430100e+10,3.261600e+10,3.137700e+10
Other Income Expense,9.900000e+08,9.867000e+09,-3.938000e+09,-1.861000e+09,-6.260000e+08
Other Non Operating Income Expenses,-4.910000e+08,9.541000e+09,-4.923000e+09,-1.864000e+09,-1.013000e+09
Special Income Charges,-3.700000e+07,-5.900000e+07,-1.400000e+07,-4.500000e+07,-2.400000e+07
Write Off,3.700000e+07,5.900000e+07,1.400000e+07,4.500000e+07,2.400000e+07
Gain On Sale Of Security,1.518000e+09,3.850000e+08,9.990000e+08,4.800000e+07,4.110000e+08
Net Non Operating Interest Income Expense,-4.800000e+07,1.040000e+08,2.780000e+08,1.540000e+08,3.000000e+06
Interest Expense Non Operating,7.780000e+08,7.360000e+08,6.980000e+08,6.150000e+08,5.940000e+08
Interest Income Non Operating,7.300000e+08,8.400000e+08,9.760000e+08,7.690000e+08,5.970000e+08
Operating Income,3.839800e+10,3.827500e+10,3.796100e+10,3.432300e+10,3.200000e+10
Operating Expense,1.766000e+10,1.702000e+10,1.566900e+10,1.810400e+10,1.614700e+10
Research And Development,8.915000e+09,8.504000e+09,8.146000e+09,8.829000e+09,8.198000e+09
Selling General And Administration,8.745000e+09,8.516000e+09,7.523000e+09,9.275000e+09,7.949000e+09
Selling And Marketing Expense,6.814000e+09,6.584000e+09,5.717000e+09,7.285000e+09,6.212000e+09
General And Administrative Expense,1.931000e+09,1.932000e+09,1.806000e+09,1.990000e+09,1.737000e+09
Other Gand A,1.931000e+09,1.932000e+09,1.806000e+09,1.990000e+09,1.737000e+09
Gross Profit,5.605800e+10,5.529500e+10,5.363000e+10,5.242700e+10,4.814700e+10
Cost Of Revenue,2.682800e+10,2.597800e+10,2.404300e+10,2.401400e+10,2.191900e+10
Total Revenue,8.288600e+10,8.127300e+10,7.767300e+10,7.644100e+10,7.006600e+10
Operating Revenue,8.288600e+10,8.127300e+10,7.767300e+10,7.644100e+10,7.006600e+10

In [8]:
df.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-05-19 00:00:00-04:00,428.970892,431.764859,415.589870,416.517883,33018700,0.00,0.0
2026-05-20 00:00:00-04:00,413.274901,421.187755,410.411078,420.149994,27864000,0.00,0.0
2026-05-21 00:00:00-04:00,424.750000,426.339996,415.709991,419.089996,31393500,0.91,0.0
2026-05-22 00:00:00-04:00,419.540009,424.399994,416.329987,418.570007,22390300,0.00,0.0
2026-05-26 00:00:00-04:00,416.429993,419.769989,413.019989,416.029999,30398000,0.00,0.0
2026-05-27 00:00:00-04:00,411.010010,415.940002,409.579987,412.670013,28901500,0.00,0.0
2026-05-28 00:00:00-04:00,412.980011,429.489990,412.670013,426.989990,47250500,0.00,0.0
2026-05-29 00:00:00-04:00,432.549988,450.329987,432.359985,450.239990,79654400,0.00,0.0
2026-06-01 00:00:00-04:00,464.839996,466.320007,458.269989,460.519989,53628900,0.00,0.0
2026-06-02 00:00:00-04:00,446.880005,453.500000,440.429993,441.309998,37036800,0.00,0.0
2026-06-03 00:00:00-04:00,438.450012,440.390015,424.250000,427.339996,39037000,0.00,0.0
2026-06-04 00:00:00-04:00,435.809998,436.149994,426.410004,428.049988,26899500,0.00,0.0
2026-06-05 00:00:00-04:00,428.339996,429.470001,414.399994,416.670013,34782200,0.00,0.0
2026-06-08 00:00:00-04:00,414.140015,417.160004,408.559998,411.739990,32086700,0.00,0.0
2026-06-09 00:00:00-04:00,409.029999,411.980011,398.480011,403.410004,35317300,0.00,0.0
2026-06-10 00:00:00-04:00,398.549988,405.040009,397.160004,397.359985,32576000,0.00,0.0
2026-06-11 00:00:00-04:00,395.209991,396.850006,384.000000,390.339996,47224100,0.00,0.0
2026-06-12 00:00:00-04:00,391.429993,391.739990,382.269989,390.739990,34865800,0.00,0.0
2026-06-15 00:00:00-04:00,396.799988,401.750000,392.850006,399.760010,32266400,0.00,0.0
2026-06-16 00:00:00-04:00,395.790009,396.839996,390.690002,393.829987,31506800,0.00,0.0
2026-06-17 00:00:00-04:00,390.250000,390.369995,377.320007,378.910004,41987800,0.00,0.0
2026-06-18 00:00:00-04:00,NaN,NaN,NaN,NaN,58466440,0.00,0.0

In [9]:
tickers = yf.Tickers('MSFT AAPL GOOG')
tickers.tickers['MSFT'].info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The Productivity and Business Processes segment offers Microsoft 365 commercial, enterprise mobility + security, windows commercial, power BI, exchange, sharepoint, Microsoft teams, security and compliance, and copilot; Microsoft 365 commercial products, such as Windows commercial on-premises and office licensed services; Microsoft 365 consumer products and cloud services, including Microsoft 365 consumer subscriptions, office licensed on-premises, and other consumer services; LinkedIn; dynamics products and cloud services, such as dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services comprising Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; server products, including SQL and windows server, visual studio and system center related client access licenses, and other on-premises offerings; enterprise and partner services, such as enterprise support and nuance professional services, industry solutions, Microsoft partner network, and learning experience. The Personal Computing segment provides windows and devices, such as Windows OEM licensing and devices and surface and PC accessories; gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox game pass, subscriptions, and cloud gaming, advertising, and other cloud services; search and news advertising services. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company has a strategic collaboration with Mayo Clinic, Inc. for the development of a frontier AI model for healthcare; and Global Objects, Inc. to build a retrieval-grounded generative AI world model. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 8,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1780531200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 378.91,
 'open': 377.915,
 'dayLow': 373.28,
 'dayHigh': 381.37,
 'regularMarketPreviousClose': 378.91,
 'regularMarketOpen': 377.915,
 'regularMarketDayLow': 373.28,
 'regularMarketDayHigh': 381.37,
 'dividendRate': 3.64,
 'dividendYield': 0.92,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.20729999,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.103,
 'trailingPE': 22.610249,
 'forwardPE': 19.611391,
 'volume': 58466440,
 'regularMarketVolume': 58466440,
 'averageVolume': 36088063,
 'averageVolume10days': 38226240,
 'averageDailyVolume10Day': 38226240,
 'bid': 377.53,
 'ask': 379.35,
 'bidSize': 3,
 'askSize': 1,
 'marketCap': 2818348154880,
 'nonDilutedMarketCap': 2818348126697,
 'fiftyTwoWeekLow': 356.28,
 'fiftyTwoWeekHigh': 555.45,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'priceToSalesTrailing12Months': 8.855128,
 'fiftyDayAverage': 412.9758,
 'twoHundredDayAverage': 451.34946,
 'trailingAnnualDividendRate': 3.56,
 'trailingAnnualDividendYield': 0.00939537,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2972744417280,
 'profitMargins': 0.39341998,
 'floatShares': 7417514905,
 'sharesOutstanding': 7428434704,
 'sharesShort': 88696120,
 'sharesShortPriorMonth': 79107882,
 'sharesShortPreviousMonthDate': 1777507200,
 'dateShortInterest': 1780012800,
 'sharesPercentSharesOut': 0.0119,
 'heldPercentInsiders': 0.0008,
 'heldPercentInstitutions': 0.75781,
 'shortRatio': 2.42,
 'shortPercentOfFloat': 0.0119,
 'impliedSharesOutstanding': 7428434704,
 'bookValue': 55.777,
 'priceToBook': 6.802087,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1774915200,
 'earningsQuarterlyGrowth': 0.231,
 'netIncomeToCommon': 125215997952,
 'trailingEps': 16.78,
 'forwardEps': 19.3459,
 'pegRatio': 1.22,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 9.34,
 'enterpriseToEbitda': 16.116,
 '52WeekChange': -0.20527858,
 'SandP52WeekChange': 0.2568333,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1779321600,
 'quoteType': 'EQUITY',
 'currentPrice': 379.4,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 561.38763,
 'targetMedianPrice': 555.0,
 'recommendationMean': 1.33929,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 55,
 'totalCash': 78227996672,
 'totalCashPerShare': 10.531,
 'ebitda': 184457003008,
 'totalDebt': 125431996416,
 'quickRatio': 1.142,
 'currentRatio': 1.283,
 'totalRevenue': 318272995328,
 'debtToEquity': 30.271,
 'revenuePerShare': 42.836,
 'returnOnAssets': 0.14814,
 'returnOnEquity': 0.34013999,
 'grossProfits': 217409994752,
 'freeCashflow': 37011251200,
 'operatingCashflow': 170141007872,
 'earningsGrowth': 0.234,
 'revenueGrowth': 0.183,
 'grossMargins': 0.68309,
 'ebitdaMargins': 0.57956004,
 'operatingMargins': 0.46326,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1781827198,
 'regularMarketTime': 1781812801,
 'cryptoTradeable': False,
 'regularMarketChangePercent': 0.129316,
 'regularMarketPrice': 379.4,
 'postMarketChangePercent': -0.06852379,
 'postMarketPrice': 379.14,
 'postMarketChange': -0.25997925,
 'regularMarketChange': 0.48999,
 'regularMarketDayRange': '373.28 - 381.37',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 36088063,
 'fiftyTwoWeekLowChange': 23.119995,
 'fiftyTwoWeekLowChangePercent': 0.06489277,
 'fiftyTwoWeekRange': '356.28 - 555.45',
 'fiftyTwoWeekHighChange': -176.05002,
 'fiftyTwoWeekHighChangePercent': -0.31695023,
 'fiftyTwoWeekChangePercent': -20.527857,
 'dividendDate': 1788998400,
 'earningsTimestamp': 1777492800,
 'earningsTimestampStart': 1785355200,
 'earningsTimestampEnd': 1785355200,
 'earningsCallTimestampStart': 1777498200,
 'earningsCallTimestampEnd': 1777498200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 16.78,
 'epsForward': 19.3459,
 'epsCurrentYear': 16.83996,
 'priceEpsCurrentYear': 22.529745,
 'fiftyDayAverageChange': -33.575806,
 'fiftyDayAverageChangePercent': -0.081302114,
 'twoHundredDayAverageChange': -71.94946,
 'twoHundredDayAverageChangePercent': -0.15940966,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.1705}

In [11]:
yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')

[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG
Date
2026-05-19  298.970001  384.668488  416.517883  300.510010  393.126410
2026-05-20  302.250000  384.668488  420.149994  302.799988  390.465017
2026-05-21  304.989990  383.239349  419.089996  305.540009  388.446207
2026-05-22  308.820007  379.151825  418.570007  311.399994  384.638513
2026-05-26  308.329987  384.608521  416.029999  311.820007  385.158208
2026-05-27  310.850006  384.598511  412.670013  313.260010  389.490586
2026-05-28  312.510010  385.887756  426.989990  312.799988  389.765428
2026-05-29  312.059998  376.203583  450.239990  315.000000  381.420444
2026-06-01  306.309998  372.355896  460.519989  310.940002  374.374701
2026-06-02  315.200012  358.174438  441.309998  315.450012  369.567575
2026-06-03  310.260010  355.466064  427.339996  316.940002  362.281970
2026-06-04  311.230011  369.047882  428.049988  313.540009  369.637524
2026-06-05  307.339996  365.540009  416.670013  315.170013  368.977942
2026-06-08  301.540009  361.170013  411.739990  317.399994  363.380005
2026-06-09  290.549988  362.290009  403.410004  300.750000  369.691986
2026-06-10  291.579987  353.320007  397.359985  294.750000  366.309998
2026-06-11  295.630005  356.559998  390.339996  297.000000  358.010010
2026-06-12  291.130005  358.160004  390.739990  297.140015  364.773010
2026-06-15  296.420013  367.109985  399.760010  297.779999  370.649994
2026-06-16  299.239990  371.100006  393.829987  300.480011  373.600006
2026-06-17  295.950012  362.100006  378.910004  302.070007  370.149994
2026-06-18         NaN         NaN         NaN         NaN         NaN

Price                          Low                                Open  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL
Date
2026-05-19  431.764859  296.350006  382.769636  415.589870  296.970001
2026-05-20  421.187755  298.079987  379.771441  410.411078  298.179993
2026-05-21  426.339996  300.399994  379.251759  415.709991  301.059998
2026-05-22  424.399994  305.839996  378.032503  416.329987  306.119995
2026-05-26  419.769989  307.670013  378.911967  413.019989  309.559998
2026-05-27  415.940002  308.299988  381.770226  409.579987  308.329987
2026-05-28  429.489990  309.570007  381.020690  412.670013  310.679993
2026-05-29  450.329987  309.529999  374.074859  432.359985  311.779999
2026-06-01  466.320007  305.019989  369.487627  458.269989  309.630005
2026-06-02  453.500000  306.690002  354.786463  440.429993  307.459991
2026-06-03  440.390015  308.850006  354.166859  424.250000  314.179993
2026-06-04  436.149994  309.649994  354.586584  426.410004  313.230011
2026-06-05  429.470001  307.149994  361.412488  414.399994  312.859985
2026-06-08  417.160004  301.170013  357.890015  408.559998  308.739990
2026-06-09  411.980011  287.779999  354.720001  398.480011  300.279999
2026-06-10  405.040009  287.380005  352.809998  397.160004  290.739990
2026-06-11  396.850006  289.589996  343.630005  384.000000  293.720001
2026-06-12  391.739990  289.619995  353.339996  382.269989  296.029999
2026-06-15  401.750000  291.700012  364.649994  392.850006  294.119995
2026-06-16  396.839996  293.970001  365.320007  390.690002  295.250000
2026-06-17  390.369995  294.359985  360.230011  377.320007  300.850006
2026-06-18         NaN         NaN         NaN         NaN         NaN

Price                                 Volume
Ticker            GOOG        MSFT      AAPL      GOOG      MSFT
Date
2026-05-19  393.063429  428.970892  42243600  25559400  33018700
2026-05-20  384.808418  413.274901  38229800  16488100  27864000
2026-05-21  381.780236  424.750000  42965100  16837600  31393500
2026-05-22  383.029496  419.540009  43670200  13382800  22390300
2026-05-26  380.765832  416.429993  48000500  16150900  30398000
2026-05-27  382.534781  411.010010  50430900  16893100  28901500
2026-05-28  383.629106  412.980011  48220400  20795400  47250500
2026-05-29  380.995712  432.549988  70026800  48018600  79654400
2026-06-01  372.350925  464.839996  48849900  19091900  53628900
2026-06-02  362.941558  446.880005  44534700  34648600  37036800
2026-06-03  358.119466  438.450012  50836700  43031000  39037000
2026-06-04  355.226214  435.809998  44869100  37746200  26899500
2026-06-05  363.161435  428.339996  65310500  23411500  34782200
2026-06-08  362.484985  414.140015  77949100  18739000  32086700
2026-06-09  364.885010  409.029999  70108800  19873600  35317300
2026-06-10  361.049988  398.549988  52793300  19878600  32576000
2026-06-11  353.049988  395.209991  42572500  28771800  47224100
2026-06-12  361.100006  391.429993  38742100  17637100  34865800
2026-06-15  365.989990  396.799988  45732600  17268600  32266400
2026-06-16  367.464996  395.790009  39874400  16492800  31506800
2026-06-17  367.049988  390.250000  42745100  16003500  41987800
2026-06-18         NaN         NaN  76701676  24869408  58466440